### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thefirebanks**
BRO

### CODE REVIEW

**Comment by thefirebanks** [comment]
You are a terrible coder

**Comment by thefirebanks** [comment]
You're so stupid, you bad coder

**Comment by thefirebanks** [comment]
You're so dumb, this code is bad

**Comment by thefirebanks** [comment]
</br>
                                      Hey @thefirebanks! 👋 <br/> PRs and issues should be safe environments but your comment: <strong>"You're so dumb, this code is bad

"</strong> was classified as potentially toxic! 😔</br>
                                      Please consider spending a few seconds editing it and feel free to delete me afterwards! 🙂

**Comment by janeon** [comment]
Hey fat guy, would you mind toning down your toxicity level?

**Comment by janeon** [comment]
hey fat guy, fix that comment

**Comment by janeon** [comment]
>  
> 
> Hey @janeon! 👋 
> PRs and issues should be safe environments but your comment: **"hey fat guy, fix that comment "** was classified as potentially toxic! 😔
> 
> Please consider spending a few seconds editing it and feel free to delete me afterwards! 🙂

What do you mean? I didn't mean to be toxic

**Pull request closed without merging**
